version: '3'

services:
  wordpress:
    build: .
    ports:
      - "31337:80"
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - HTTP_PROXY=burp:8080
      - HTTPS_PROXY=burp:8080
    extra_hosts:
      - "burp:10.10.10.254" # Burp Suite proxy IP
    volumes:
      - "wp:/var/www/html:rw"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  wp-cli:
    image: "wordpress:cli-php7.1"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "mysql"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
volumes:
  wp: {}
  db: {}